openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8081
    description: root url
paths:
  /service-provider:
    post:
      tags:
        - service provider
      summary: Add a new Service Provider
      description: Add a new Service Provider to provide review for/against
      operationId: addServiceProvider
      requestBody:
        description: Create a new Service Provider
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestSpDto'
        required: true
      responses:
        '201':
          description: Service Provider successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSpDto'
    get:
      tags:
        - service provider
      summary: Retrieve all Service Providers
      description: Retrieve all the Service Providers present in database
      operationId: retrieveAllServiceProviders
      responses:
        200:
          description: All Service Providers retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseSpDto'
  /service-provider/{id}:
    get:
      tags:
        - service provider
      summary: Retrieve Service Provider by Id
      description: Retrieves Service Provider based on the spId provided
      operationId: retrieveServiceProvider
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSpDto'
        404:
          description: Service Provider not found
    put:
      tags:
        - service provider
      summary: Updates Service Provider by Id
      description: Updates Service Provider based on the spId provided
      operationId: updateServiceProvider
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestSpDto'
        required: true
      responses:
        200:
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSpDto'
        404:
          description: Service Provider not found
    delete:
      tags:
        - service provider
      summary: Delete Service Provider by Id
      description: Deletes Service Provider based on the spId provided
      operationId: deleteServiceProvider
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Successful Operation, with No Content returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSpDto'
        404:
          description: Service Provider not found
components:
  schemas:
    RequestSpDto:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        address:
          type: string
        phoneNo:
          type: string
        category:
          type: string
    ResponseSpDto:
      type: object
      properties:
        spId:
          type: string
        email:
          type: string
        name:
          type: string
        address:
          type: string
        phoneNo:
          type: string
        category:
          type: string
